/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void vassume(int b ) 
{ 


  {
  return;
}
}
void vtrace1(int _xeq1 , int _xeq0 ) 
{ 


  {
  return;
}
}
void vtrace2(int _xeq1 , int _xeq0 ) 
{ 


  {
  return;
}
}
int mainQ(int c , int n ) 
{ 
  int c2 ;
  int x ;
  int r ;
  int j1 ;
  int _xeq1 ;
  int _xeq0 ;
  int c1 ;
  int _atomic0 ;

  {
  vassume(c >= 0);
  _atomic0 = y == 0;
  vtrace16(_atomic0);
  c2 = c;
  _atomic0 = y == 0;
  vtrace18(_atomic0);
  r = 0;
  _atomic0 = y == 0;
  vtrace19(_atomic0);
  j1 = 0;
  _atomic0 = y == 0;
  vtrace20(_atomic0);
  _xeq1 = 0;
  _atomic0 = y == 0;
  vtrace21(_atomic0);
  _xeq0 = 0;
  _atomic0 = y == 0;
  vtrace22(_atomic0);
  while (j1 <= 50) {
    j1 ++;
    _atomic0 = y == 0;
    vtrace24(_atomic0);
    c1 = c;
    _atomic0 = y == 0;
    vtrace25(_atomic0);
    while (c1 > 0) {
      r += c1;
      _atomic0 = y == 0;
      vtrace27(_atomic0);
      c1 --;
      _atomic0 = y == 0;
      vtrace28(_atomic0);
    }
    x = ((2 * r - c * c) - c) + 1;
    _atomic0 = y == 0;
    vtrace29(_atomic0);
    _xeq1 = x == 1;
    _atomic0 = y == 0;
    vtrace29(_atomic0);
    _xeq0 = x == 0;
    _atomic0 = y == 0;
    vtrace29(_atomic0);
    vtrace1(_xeq1, _xeq0);
    _atomic0 = y == 0;
    vtrace30(_atomic0);
    while (n > 0) {
      n --;
      _atomic0 = y == 0;
      vtrace32(_atomic0);
    }
    r = 0;
    _atomic0 = y == 0;
    vtrace33(_atomic0);
    while (c2 > 0) {
      r += c2;
      _atomic0 = y == 0;
      vtrace35(_atomic0);
      c2 --;
      _atomic0 = y == 0;
      vtrace36(_atomic0);
    }
    x = (2 * r - c * c) - c;
    _atomic0 = y == 0;
    vtrace38(_atomic0);
    _xeq1 = x == 1;
    _atomic0 = y == 0;
    vtrace38(_atomic0);
    _xeq0 = x == 0;
    _atomic0 = y == 0;
    vtrace38(_atomic0);
    vtrace2(_xeq1, _xeq0);
    _atomic0 = y == 0;
    vtrace39(_atomic0);
  }
  return (0);
}
}
extern int ( /* missing proto */  atoi)() ;
void main(int argc , char **argv ) 
{ 
  int tmp ;
  int tmp___0 ;

  {
  tmp = atoi(*(argv + 2));
  tmp___0 = atoi(*(argv + 1));
  mainQ(tmp___0, tmp);
  return;
}
}
