/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#line 6 "simple_gf.c"
void vassume(int b ) 
{ 


  {
#line 6
  return;
}
}
#line 9 "simple_gf.c"
void vtrace1(int _xeq1 , int _xeq0 ) 
{ 


  {
#line 9
  return;
}
}
#line 10 "simple_gf.c"
void vtrace2(int _xeq1 , int _xeq0 ) 
{ 


  {
#line 10
  return;
}
}
#line 15 "simple_gf.c"
int mainQ(int c , int n ) 
{ 
  int c2 ;
  int x ;
  int r ;
  int j1 ;
  int _xeq1 ;
  int _xeq0 ;
  int c1 ;
  int atomX ;
  int atomY ;

  {
#line 16
  vassume(c >= 0);
#line 16
  atomX += 2;
#line 16
  atomY += 2;
#line 18
  c2 = c;
#line 18
  atomX += 2;
#line 18
  atomY += 2;
#line 19
  r = 0;
#line 19
  atomX += 2;
#line 19
  atomY += 2;
#line 20
  j1 = 0;
#line 20
  atomX += 2;
#line 20
  atomY += 2;
#line 21
  _xeq1 = 0;
#line 21
  atomX += 2;
#line 21
  atomY += 2;
#line 22
  _xeq0 = 0;
#line 22
  atomX += 2;
#line 22
  atomY += 2;
#line 23
  while (j1 <= 50) {
#line 24
    j1 ++;
#line 24
    atomX += 2;
#line 24
    atomY += 2;
#line 25
    c1 = c;
#line 25
    atomX += 2;
#line 25
    atomY += 2;
#line 26
    while (c1 > 0) {
#line 27
      r += c1;
#line 27
      atomX += 2;
#line 27
      atomY += 2;
#line 28
      c1 --;
#line 28
      atomX += 2;
#line 28
      atomY += 2;
    }
#line 29
    x = ((2 * r - c * c) - c) + 1;
#line 29
    atomX += 2;
#line 29
    atomY += 2;
#line 29
    _xeq1 = x == 1;
#line 29
    atomX += 2;
#line 29
    atomY += 2;
#line 29
    _xeq0 = x == 0;
#line 29
    atomX += 2;
#line 29
    atomY += 2;
#line 30
    vtrace1(_xeq1, _xeq0);
#line 30
    atomX += 2;
#line 30
    atomY += 2;
#line 32
    while (n > 0) {
#line 32
      n --;
#line 32
      atomX += 2;
#line 32
      atomY += 2;
    }
#line 33
    r = 0;
#line 33
    atomX += 2;
#line 33
    atomY += 2;
#line 34
    while (c2 > 0) {
#line 35
      r += c2;
#line 35
      atomX += 2;
#line 35
      atomY += 2;
#line 36
      c2 --;
#line 36
      atomX += 2;
#line 36
      atomY += 2;
    }
#line 38
    x = (2 * r - c * c) - c;
#line 38
    atomX += 2;
#line 38
    atomY += 2;
#line 38
    _xeq1 = x == 1;
#line 38
    atomX += 2;
#line 38
    atomY += 2;
#line 38
    _xeq0 = x == 0;
#line 38
    atomX += 2;
#line 38
    atomY += 2;
#line 39
    vtrace2(_xeq1, _xeq0);
#line 39
    atomX += 2;
#line 39
    atomY += 2;
  }
#line 41
  return (0);
}
}
#line 44
extern int ( /* missing proto */  atoi)() ;
#line 43 "simple_gf.c"
void main(int argc , char **argv ) 
{ 
  int tmp ;
  int tmp___0 ;

  {
#line 44
  tmp = atoi(*(argv + 2));
#line 44
  tmp___0 = atoi(*(argv + 1));
#line 44
  mainQ(tmp___0, tmp);
#line 45
  return;
}
}
