/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#include "stdio.h"
#include "stdlib.h"
#include "assert.h"
#include "math.h"
int mainQ(int i ) 
{ 
  int x ;
  int y ;
  int a ;

  {
  x = 0;
  vtrace7(x, y, a);
  y = 0;
  vtrace7(x, y, a);
  a = 0;
  vtrace8(x, y, a);
  x = i;
  vtrace9(x, y, a);
  y = 2;
  vtrace10(x, y, a);
  a = 0;
  vtrace11(x, y, a);
  while (a < 10) {
    x = 1;
    vtrace13(x, y, a);
    y = 1;
    vtrace14(x, y, a);
    while (x > 0) {
      x --;
      vtrace16(x, y, a);
    }
    y = 0;
    vtrace19(x, y, a);
    a ++;
    vtrace21(x, y, a);
  }
  return (y);
}
}
extern int ( /* missing proto */  atoi)() ;
void main(int argc , char **argv ) 
{ 
  int tmp ;

  {
  tmp = atoi(*(argv + 1));
  mainQ(tmp);
  return;
}
}
