/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#include "stdio.h"
#include "stdlib.h"
#include "assert.h"
#include "math.h"



void vtrace9(int x, int y, int a, int atomic0){}
void vtrace10(int x, int y, int a, int atomic0){}
void vtrace11(int x, int y, int a, int atomic0){}
void vtrace13(int x, int y, int a, int atomic0){}
void vtrace14(int x, int y, int a, int atomic0){}
void vtrace16(int x, int y, int a, int atomic0){}
void vtrace19(int x, int y, int a, int atomic0){}
void vtrace20(int x, int y, int a, int atomic0){}
void vtrace21(int x, int y, int a, int atomic0){}

int mainQ(int i ){
    int x;
    int y;
    int a;
    int atomic0;

    x = i;
    /* atomic0 = y == 0; */
    /* vtrace9(x, y, a, atomic0); */
    y = 2;
    /* atomic0 = y == 0; */
    /* vtrace10(x, y, a, atomic0); */
    a = 0;
    atomic0 = y == 0;
    vtrace11(x, y, a, atomic0);
    while (a < 10) {
        x = 1;
        atomic0 = y == 0;
        vtrace13(x, y, a, atomic0);
        y = 1;
        atomic0 = y == 0;
        vtrace14(x, y, a, atomic0);
        while (x > 0) {
            x --;
            atomic0 = y == 0;
            vtrace16(x, y, a, atomic0);
        }
        y = 0;
        atomic0 = y == 0;
        vtrace19(x, y, a, atomic0);
        /* vtrace(x, y); */
        atomic0 = y == 0;
        vtrace20(x, y, a, atomic0);
        a ++;
        atomic0 = y == 0;
        vtrace21(x, y, a, atomic0);
    }
    return (y);
}


void main(int argc, char **argv) {
    //mainQ(atoi(argv[1]), atoi(argv[2]), atoi(argv[3]));
    mainQ(atoi(argv[1]));
}
