alg:WARNING:vtrace9: no symbolic states. Skip
alg:WARNING:vtrace10: no symbolic states. Skip
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=1,y=2,a=0,atomic0=0 exist
data.traces:WARNING:trace x=1,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=1,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=1,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=1,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=5,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=2,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=6,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=1,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=7,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=0,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=9,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=4,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=8,atomic0=0 exist
data.traces:WARNING:trace x=0,y=1,a=3,atomic0=0 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=0,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=9,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=10,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=3,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=6,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=7,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=8,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=1,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=2,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=4,atomic0=1 exist
data.traces:WARNING:trace x=0,y=0,a=5,atomic0=1 exist
* prog test1.c.encode locs 7;  invs 52 (Eqt: 20, Oct: 32) V 4 T 3 D 1;  NL 0 (1) ;
-> time eqts 2.8s, ieqs 3.2s, simplify 1.6s, symbolic_states 19.3s, total 27.6s
-> checks  0 () change depths 0 () change vals 0 ()
-> max  0 () change depths 0 ()
runs 1
rand seed 1627488539.6, test (22, 93)
vtrace11 (7 invs):
1. a == 0
2. y - 2 == 0
3. atomic0 == 0
4. a <= 0
5. -a <= 0
6. atomic0 <= 0
7. -atomic0 <= 0
vtrace13 (6 invs):
1. x - 1 == 0
2. 2*atomic0 + y - 2 == 0
3. -y <= 0
4. -atomic0 <= 0
5. atomic0 - x <= 0
6. -a + atomic0 <= 0
vtrace14 (8 invs):
1. y - 1 == 0
2. x - 1 == 0
3. atomic0 == 0
4. -a <= 0
5. x - y <= 0
6. -x + y <= 0
7. atomic0 <= 0
8. -atomic0 <= 0
vtrace16 (7 invs):
1. x == 0
2. y - 1 == 0
3. atomic0 == 0
4. -x <= 0
5. -a <= 0
6. atomic0 <= 0
7. -atomic0 + x <= 0
vtrace19 (8 invs):
1. y == 0
2. x == 0
3. atomic0 - 1 == 0
4. x <= 0
5. -x <= 0
6. -a <= 0
7. x + y <= 0
8. -x - y <= 0
vtrace20 (8 invs):
1. y == 0
2. x == 0
3. atomic0 - 1 == 0
4. x <= 0
5. -x <= 0
6. -a <= 0
7. x + y <= 0
8. -x - y <= 0
vtrace21 (8 invs):
1. y == 0
2. x == 0
3. atomic0 - 1 == 0
4. x <= 0
5. -x <= 0
6. x + y <= 0
7. -x - y <= 0
8. -a + atomic0 <= 0
tmpdir: /var/tmp/dig_1383505587253379355_m9v7m7ua
